"""add student_id_photo to user

Revision ID: 287a4234b262
Revises: d3ca247da342
Create Date: 2026-08-05 12:16:04.623466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287a4234b262'
down_revision = 'd3ca247da342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id_photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('student_id_photo')

    # ### end Alembic commands ###
