"""add site stats table

Revision ID: 9641aaa28a62
Revises: 287a4234b262
Create Date: 2026-08-05 12:39:22.655426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9641aaa28a62'
down_revision = '287a4234b262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_visits', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_stat')
    # ### end Alembic commands ###
