"""add author_id to english_resource

Revision ID: d3ca247da342
Revises: c6d9e0f1a232
Create Date: 2026-08-05 11:58:56.882543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ca247da342'
down_revision = 'c6d9e0f1a232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('english_resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_english_resource_author_id'), ['author_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('english_resource', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_english_resource_author_id'))
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
