"""add survey center

Revision ID: f1fa31601f68
Revises: fa842f125001
Create Date: 2026-08-01 20:48:58.231848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fa31601f68'
down_revision = 'fa842f125001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('allow_anonymous', sa.Boolean(), nullable=False),
    sa.Column('require_login', sa.Boolean(), nullable=False),
    sa.Column('allow_edit', sa.Boolean(), nullable=False),
    sa.Column('allow_repeat', sa.Boolean(), nullable=False),
    sa.Column('use_account_profile_data', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('success_message', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_survey_status'), ['status'], unique=False)

    op.create_table('survey_access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('anonymous_token', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('visited_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_access_log', schema=None) as batch_op:
        batch_op.create_index('idx_survey_access_visited', ['survey_id', 'visited_at'], unique=False)

    op.create_table('survey_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('question_type', sa.String(length=40), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('validation_rules_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_question', schema=None) as batch_op:
        batch_op.create_index('idx_survey_question_order', ['survey_id', 'sort_order'], unique=False)

    op.create_table('survey_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anonymous_token', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('completion_seconds', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.create_index('idx_survey_response_submitted', ['survey_id', 'submitted_at'], unique=False)
        batch_op.create_index('idx_survey_response_user', ['survey_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_response_anonymous_token'), ['anonymous_token'], unique=False)

    op.create_table('survey_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['survey_question.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['survey_response.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'question_id', name='uq_survey_answer_response_question')
    )
    op.create_table('survey_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['survey_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_option', schema=None) as batch_op:
        batch_op.create_index('idx_survey_option_order', ['question_id', 'sort_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_option', schema=None) as batch_op:
        batch_op.drop_index('idx_survey_option_order')

    op.drop_table('survey_option')
    op.drop_table('survey_answer')
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_response_anonymous_token'))
        batch_op.drop_index('idx_survey_response_user')
        batch_op.drop_index('idx_survey_response_submitted')

    op.drop_table('survey_response')
    with op.batch_alter_table('survey_question', schema=None) as batch_op:
        batch_op.drop_index('idx_survey_question_order')

    op.drop_table('survey_question')
    with op.batch_alter_table('survey_access_log', schema=None) as batch_op:
        batch_op.drop_index('idx_survey_access_visited')

    op.drop_table('survey_access_log')
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_status'))
        batch_op.drop_index(batch_op.f('ix_survey_slug'))

    op.drop_table('survey')
    # ### end Alembic commands ###
